
spacer: spacer.o render.o raster.o events.o model.o clear_qk.o svisor.o video.o
	cc68x -g spacer.o render.o raster.o events.o model.o clear_qk.o svisor.o video.o -o run_game

spacer.o: spacer.c
	cc68x -g -c spacer.c

render.o: render.c includes\render.h 
	cc68x -g -c render.c
	
raster.o: raster.c includes\raster.h
	cc68x -g -c raster.c

events.o: events.c includes\events.h
	cc68x -g -c events.c

model.o: model.c includes\model.h
	cc68x -g -c model.c 

psg.o: psg.c includes\psg.h
	cc68x -g -c psg.c

music.o: music.c includes\music.h
	cc68x -g -c music.c

clear_qk.o: clear_qk.s includes\clear_qk.h
	gen -D -L2 clear_qk.s
	
video.o: video.s includes\video.h 
	gen -D -L2 video.s -ovideo.o
	
svisor.o: svisor.s 
	gen -D -L2 svisor.s -osvisor.o
	
tst_rast: tst_rast.o raster.o
	cc68x -g tst_rast.o raster.o -o tst_rast

tst_rast.o: tst_rast.c includes\raster.h
	cc68x -g -c tst_rast.c
	
tst_modl: tst_modl.o events.o model.o
	cc68x -g tst_modl.o events.o model.o -o tst_modl

tst_modl.o: tst_modl.c includes\model.h includes\events.h
	cc68x -g -c tst_modl.c
